Milestone two: Components, Containers and Reducer
george-shammar/bookstore-cmss pull request #4
Opened 2021-07-23 22:46 UTC by george-shammar

This Pull Request seeks to merge the following changes to the development branch:
1. Implemented Container with BooksList.js and BooksForm.js
2. Implemented Component with App.js and books.js.
3. Implemented Actions (createBook and removeBook) with corresponding reducer.
4. Initialize redux store.
5. Rendered the <App/> component wrapped in <Provider> and passed the store down to the components.

2021-07-24 03:20 UTC, voscarmv requested changes
# Impressive work.  💻 👀 ✨

## However, there are some changes required 👀 🧰 🔨 🔧
- Passing linter tests is a prerequisite for every project. As such, linter bypassing should be discouraged. I ran your project and I noticed that removing some of the linter disabler lines in your code did not trigger the linter.
- Please update the Live Demo link in your README file. It currently points to a previous version of the project.

### Submit these changes and request a new code review! 😄 👍

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier)🧑‍💻🗨️🧑‍💻
# Happy Coding! 🧠 ⌨️ 🖱️ 🖥️

2021-07-24 03:20 UTC, voscarmv commented on src/containers/BooksForm.js
> +/* eslint-disable jsx-a11y/label-has-associated-control */
- [ ] Please remove all linter disabler lines. Try to find fixes for the issues instead of bypassing them.

2021-07-24 03:20 UTC, voscarmv commented on src/containers/BooksList.js
> +/* eslint-disable */
- [ ] Please remove linter disabling lines.

2021-07-24 03:20 UTC, voscarmv commented on src/index.js
> +import App from './components/App'; /* eslint-disable-line  import/no-cycle */
- [ ] Please remove linter disabling lines.

2021-07-24 03:20 UTC, voscarmv commented on src/components/App.js
> +import BooksList from '../containers/BooksList'; /* eslint-disable-line  import/no-cycle */
- [ ] Please remove all liner disabling lines.

2021-07-24 06:03 UTC, voscarmv reviewed
Hi, it's me again. I forgot to point out a few more mandatory requirements:

- [ ] The file `src/reducers/index.js` is empty. It's supposed to combine the app-specific reducers.
- [ ] Please fix all the issues found in my code comments.

2021-07-24 06:03 UTC, voscarmv commented on src/containers/BooksList.js
> +            <tr key={i}>
- [ ] Please don't use index numbers for keys. Instead you can use a unique attribute of the `book` object. I noticed you use `Math.random()` to generate the bookId attribute. You can use `key={book.id}` instead of `key={i}`.

2021-07-26 20:01 UTC, bellom approved these changes
## Hi @george-shammar :clap: 

**Great work making all the necessary corrections from the previous review.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

**Best,**

2021-07-26 20:01 UTC, bellom commented on src/reducers/books.js
> +};
### [Optional]

This is tag optional because for some reason the previous didn't drop a comment on this.

Let's remove the sample books create in this file, it should be in ``src/index.js`

According to the instructions on pathwright, I think you need to move the `initialState` into `src/index.js`

![image](https://user-images.githubusercontent.com/31897434/122143582-a6b8de80-ce49-11eb-86a3-ffbf2e5e22d4.png)

[Pathwright](https://microverse.pathwright.com/library/react-redux-v11/184438/path/step/106376028/)

2021-07-26 20:19 UTC, merged